name: Video Uploader Bot

on:
  workflow_dispatch:      # Manual button
  schedule:
    - cron: '0 */6 * * *' # Auto run every 6 hours

jobs:
  run-uploader:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install -r requirements.txt

      - name: Run Bot Script
        env:
          G_CLIENT_SECRET: ${{ secrets.G_CLIENT_SECRET }}
          G_REFRESH_TOKEN: ${{ secrets.G_REFRESH_TOKEN }}
          DRIVE_QUEUE_FOLDER: ${{ secrets.DRIVE_QUEUE_FOLDER }}
          DRIVE_DONE_FOLDER: ${{ secrets.DRIVE_DONE_FOLDER }}
          INSTA_USERNAME: ${{ secrets.INSTA_USERNAME }}
          INSTA_PASSWORD: ${{ secrets.INSTA_PASSWORD }}
          INSTA_SETTINGS: ${{ secrets.INSTA_SETTINGS }}  # <-- Ye line zaroori hai!
        run: python main.py
