name: Video Uploader Bot

on:
  workflow_dispatch:      # Manual run button
  schedule:
    # 4 Baar chalega: 8 AM, 12 PM, 4 PM, 8 PM (India Time)
    - cron: '30 2,6,10,14 * * *'

jobs:
  run-uploader:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Latest version use karein

      - name: Set up Python
        uses: actions/setup-python@v5 # Latest version use karein
        with:
          python-version: '3.10'
          cache: 'pip' # Dependencies cache karega taaki baar baar install na ho

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
        # Ye step MoviePy ke liye sabse zaroori hai

      - name: Install Libraries
        run: pip install -r requirements.txt

      - name: Run Bot Script
        env:
          G_CLIENT_SECRET: ${{ secrets.G_CLIENT_SECRET }}
          G_REFRESH_TOKEN: ${{ secrets.G_REFRESH_TOKEN }}
          DRIVE_QUEUE_FOLDER: ${{ secrets.DRIVE_QUEUE_FOLDER }}
          DRIVE_DONE_FOLDER: ${{ secrets.DRIVE_DONE_FOLDER }}
          INSTA_USERNAME: ${{ secrets.INSTA_USERNAME }}
          INSTA_PASSWORD: ${{ secrets.INSTA_PASSWORD }}
          INSTA_SETTINGS: ${{ secrets.INSTA_SETTINGS }}
        run: python main.py
